title: Mug'Ink
name: "Mugoh's Blog"
author: Mugoh Mwaura
twitter_username: mugoh_ks
baseurl: "/log"
description: A space to document my learning 
profile_url: "http://mugoh.github.io"
image:
    path: /assets/images/profile_pic_400x400.png
    height: 50
    width: 50

disqus:
    shortname: mug-log

url: https://mugoh.github.io/log
repository: mugoh/mugoh.github.io

# Build settings
markdown: kramdown
highlighter: rouge
excerpt_separator: <!--more-->
plugins:
  - jekyll-feed
  - jekyll-archives
  - jemoji
exclude:
  - Gemfile
  - Gemfile.lock
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

permalink: /:title/

collections_dir: misc

collections:
    school-work:
        output: true
        permalink: /:collection/:name/
    posts:
        output: true
    paper-summaries:
        output: true
        permalink: /:collection/:name/
        sort_by: date
    ml-interviews-book:
        output: true
        permalink: /:collection/:name/
        sort_by: date
